services:
  - type: web
    name: recommendation-app
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn run:app --workers=2 --threads=2 --timeout=120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: recommendation-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false

databases:
  - name: recommendation-db
    databaseName: recommendation
    ipAllowList: []  # Only allow internal connections 